# This is mostly run by Cirrus's cron feature
# See builds at https://cirrus-ci.com/github/xonsh/container
docker_builder:
  only_if: $CIRRUS_BRANCH == 'main'
  env:
    # FIXME: Use a dedicated bot account
    DOCKER_USERNAME: ENCRYPTED[2d73b3858060181e74628f1f6bab14ed322014a4cb54ba3fd1d5870caca4e41e8e9cee571f78c00068c0d11a21107003]
    DOCKER_PASSWORD: ENCRYPTED[6e3a3fcc75e878c41e9dca56c44e7c0986859f385df31103a93805122ce2033fbf9f3209bd5b6b21f364914dfeaaf3e2]
  login_script:
    - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  build_script:
    - ./rebuild.py
