#~cirrus-ci~

query get_repo_with_builds(
  $owner: String!
  $name: String!
  $branch: String
) {
  githubRepository(owner: $owner, name: $name) {
    id
    owner
    name
    masterBranch
    builds(last: 1, branch: $branch) {
      edges {
        node {
          id
          status
          tasks {
              id
              name
              status
          }
        }
      }
    }
  }
}



mutation pull_task_trigger($task: ID!) {
  trigger(input: {
    taskId: $task
  }) {
    task {
      id
    }
  }
}


mutation start_fresh_build(
  $repo: ID!
  $branch: String!
  $sha: String
) {
  createBuild(input: {
    repositoryId: $repo
    branch: $branch
    sha: $sha
    # configOverride  # What is this??
  }) {
    build {
      id
    }
  }
}
