FROM xonsh/xonsh{colonvariant}

LABEL "repository"="http://github.com/xonsh/container"
LABEL "homepage"="https://xon.sh/"
LABEL "maintainer"="Jamie Bliss <jamie@ivyleav.es>"

RUN xpip install xonsh[linux,ptk,pygments]{specifier}
COPY interactive.xsh /etc/xonshrc

CMD ["/usr/bin/xonsh"]
